spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/civicsense_db
spring.datasource.username=civicsense_user
spring.datasource.password=civicsense_password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8031
spring.flyway.enabled=false
jwt.secret=civicsense_super_secret_key_please_change_later_123456
jwt.expiration=604800000
file.upload-dir=uploads

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=civicsense-ai-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.properties.spring.json.trusted.packages=com.civicsense.backend.dto
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.kafka.topic.issue-image-uploaded=issue-image-uploaded

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB